# Generated by Django 2.1.7 on 2019-05-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='data',
            new_name='data_of_buy',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='name',
            new_name='name_of_buy',
        ),
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
