# Generated by Django 2.1.7 on 2019-05-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_orders_price_of_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Добавлен'), (1, 'Подтвержден'), (2, 'Готов')], default=0, null=True),
        ),
    ]
