# Generated by Django 2.1.7 on 2019-06-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Доб.'), (1, 'Подтв.'), (2, 'Гот.')], default=0, null=True),
        ),
    ]
