# Generated by Django 2.1.7 on 2019-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0007_auto_20190607_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price_of_buy',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
