# Generated by Django 2.1.7 on 2019-06-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_auto_20190608_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price_of_buy',
            field=models.IntegerField(default=1),
        ),
    ]
